/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Trivial liveness check.
         */
        get: operations["health__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/screenings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Screenings
         * @description List the most recent screenings, newest first.
         *
         *     With the job queue enabled every screening starts as a job, so the
         *     list is built from jobs (including ones still ``pending``/``running``)
         *     and uses the same ids ``POST`` returned; otherwise from analysis runs.
         */
        get: operations["list_screenings_v1_screenings_get"];
        put?: never;
        /**
         * Create Screening
         * @description Create a screening.
         *
         *     Without ``DATABASE_URL`` (Step 1): runs synchronously, like the CLI, and
         *     returns ``201`` with the completed result. With ``DATABASE_URL`` (Step
         *     3): only validates the input, enqueues a job and returns ``202`` with a
         *     ``pending`` summary — a worker process picks it up and ``GET`` polls for
         *     the outcome.
         */
        post: operations["create_screening_v1_screenings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/screenings/{screening_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Screening
         * @description Look up a previously created screening by id.
         *
         *     ``screening_id`` is either an ``AnalysisRun`` id (sync mode, or async
         *     mode once resolved) or — only when the job queue is enabled — a job id
         *     that has not resolved to a run yet (``pending``/``running``).
         */
        get: operations["get_screening_v1_screenings__screening_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/screenings/{screening_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Screening Report
         * @description Render the plain-text report for a completed screening.
         */
        get: operations["get_screening_report_v1_screenings__screening_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/screenings/{screening_id}/layers/{layer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Screening Layer
         * @description Return one result layer as GeoJSON, for map display.
         */
        get: operations["get_screening_layer_v1_screenings__screening_id__layers__layer__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/screenings/{screening_id}/technologies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Technology Results
         * @description Return every wind/solar/hybrid/battery result stored for a screening.
         */
        get: operations["get_technology_results_v1_screenings__screening_id__technologies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/screenings/{screening_id}/turbine-layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Turbine Layout
         * @description Place turbines on a completed screening's available area and, given a
         *     wind resource, simulate their production — same use cases as the CLI's
         *     ``--turbine-catalog``/``--wind-resource`` options.
         *
         *     Runs synchronously (docs/WEB_ARCHITECTURE.md section 4.3: orders of
         *     magnitude faster than the screening itself). Replaces any earlier wind
         *     result for this screening and clears the hybrid and battery results
         *     that were derived from it.
         */
        post: operations["create_turbine_layout_v1_screenings__screening_id__turbine_layout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/screenings/{screening_id}/solar-array": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Solar Array
         * @description Size a PV array on a completed screening's available area and, given a
         *     solar resource, simulate its production — same use cases as the CLI's
         *     ``--solar-catalog``/``--solar-resource`` options.
         *
         *     Synchronous; replaces any earlier solar result for this screening and
         *     clears the hybrid and battery results that were derived from it.
         */
        post: operations["create_solar_array_v1_screenings__screening_id__solar_array_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/screenings/{screening_id}/hybrid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Hybrid
         * @description Combine the stored wind and/or solar production profiles and clip the
         *     total to the grid connection limit (CLI: ``--grid-connection-limit-mw``).
         *
         *     Requires at least one of ``turbine-layout``/``solar-array`` to have run
         *     with a resource file, so there is a production profile to aggregate.
         *     Clears the battery result derived from an earlier hybrid result.
         */
        post: operations["create_hybrid_v1_screenings__screening_id__hybrid_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/screenings/{screening_id}/battery-dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Battery Dispatch
         * @description Dispatch a battery against the stored hybrid aggregate profile, with
         *     the hybrid grid connection limit as target power (CLI:
         *     ``--battery-catalog``). Requires a hybrid result.
         */
        post: operations["create_battery_dispatch_v1_screenings__screening_id__battery_dispatch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BatteryResult
         * @description Outcome of ``POST /v1/screenings/{id}/battery-dispatch``.
         */
        BatteryResult: {
            /** Battery Manufacturer */
            battery_manufacturer: string;
            /** Battery Model */
            battery_model: string;
            /** Target Power Mw */
            target_power_mw: number;
            /** Initial State Of Charge Fraction */
            initial_state_of_charge_fraction: number;
            /** Charged Energy Mwh */
            charged_energy_mwh: number;
            /** Discharged Energy Mwh */
            discharged_energy_mwh: number;
            /** Round Trip Loss Mwh */
            round_trip_loss_mwh: number;
            /** Curtailed Energy Mwh */
            curtailed_energy_mwh: number;
            /** Final State Of Charge Fraction */
            final_state_of_charge_fraction: number;
            delivered_profile: components["schemas"]["ProfileSeries"];
            /** State Of Charge Fraction */
            state_of_charge_fraction: number[];
        };
        /** Body_create_battery_dispatch_v1_screenings__screening_id__battery_dispatch_post */
        Body_create_battery_dispatch_v1_screenings__screening_id__battery_dispatch_post: {
            /**
             * Battery Catalog
             * @description Katalog magazynów (YAML/JSON)
             */
            battery_catalog: string;
            /** Battery Manufacturer */
            battery_manufacturer?: string | null;
            /** Battery Model */
            battery_model?: string | null;
            /** Initial State Of Charge Fraction */
            initial_state_of_charge_fraction?: number | null;
        };
        /** Body_create_hybrid_v1_screenings__screening_id__hybrid_post */
        Body_create_hybrid_v1_screenings__screening_id__hybrid_post: {
            /** Grid Connection Limit Mw */
            grid_connection_limit_mw: number;
        };
        /** Body_create_screening_v1_screenings_post */
        Body_create_screening_v1_screenings_post: {
            /**
             * Site
             * @description Granica terenu (GeoJSON)
             */
            site: string;
            /**
             * Constraints
             * @description Warstwy ograniczeń (GeoJSON)
             */
            constraints: string;
            /**
             * Rules
             * @description Konfiguracja reguł (YAML)
             */
            rules: string;
            /** Technology */
            technology: string;
            /**
             * Country
             * @default PL
             */
            country: string;
            /** Analysis Date */
            analysis_date?: string | null;
        };
        /** Body_create_solar_array_v1_screenings__screening_id__solar_array_post */
        Body_create_solar_array_v1_screenings__screening_id__solar_array_post: {
            /**
             * Solar Catalog
             * @description Katalog modułów PV (YAML/JSON)
             */
            solar_catalog: string;
            /** Ground Coverage Ratio */
            ground_coverage_ratio: number;
            /** Solar Manufacturer */
            solar_manufacturer?: string | null;
            /** Solar Model */
            solar_model?: string | null;
            /**
             * Solar Resource
             * @description Godzinowy szereg nasłonecznienia (YAML/JSON)
             */
            solar_resource?: string | null;
            /**
             * Use Pvlib
             * @default false
             */
            use_pvlib: boolean;
            /**
             * Technical Availability
             * @default 1
             */
            technical_availability: number;
            /**
             * Loss Factor
             * @default 0
             */
            loss_factor: number;
        };
        /** Body_create_turbine_layout_v1_screenings__screening_id__turbine_layout_post */
        Body_create_turbine_layout_v1_screenings__screening_id__turbine_layout_post: {
            /**
             * Turbine Catalog
             * @description Katalog turbin (YAML/JSON)
             */
            turbine_catalog: string;
            /** Spacing Rotor Diameters */
            spacing_rotor_diameters: number;
            /** Grid Spacing M */
            grid_spacing_m?: number | null;
            /** Turbine Manufacturer */
            turbine_manufacturer?: string | null;
            /** Turbine Model */
            turbine_model?: string | null;
            /**
             * Wind Resource
             * @description Godzinowy szereg wiatru (YAML/JSON)
             */
            wind_resource?: string | null;
            /**
             * Use Pywake
             * @default false
             */
            use_pywake: boolean;
            /**
             * Technical Availability
             * @default 1
             */
            technical_availability: number;
            /**
             * Loss Factor
             * @default 0
             */
            loss_factor: number;
        };
        /**
         * FindingSummary
         * @description One constraint finding, shaped for JSON responses.
         */
        FindingSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Constraint Id
             * Format: uuid
             */
            constraint_id: string;
            /** Level */
            level: string;
            /** Status */
            status: string;
            /** Data Source */
            data_source: string;
            /** Data Version */
            data_version: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HybridResult
         * @description Outcome of ``POST /v1/screenings/{id}/hybrid``.
         */
        HybridResult: {
            /** Grid Connection Limit Mw */
            grid_connection_limit_mw: number;
            /** Sources */
            sources: string[];
            /** Aggregate Energy Mwh */
            aggregate_energy_mwh: number;
            /** Delivered Energy Mwh */
            delivered_energy_mwh: number;
            /** Curtailed Energy Mwh */
            curtailed_energy_mwh: number;
            /** Curtailed Energy Fraction */
            curtailed_energy_fraction: number;
            /** Utilization Fraction */
            utilization_fraction: number;
            aggregate_profile: components["schemas"]["ProfileSeries"];
            delivered_profile: components["schemas"]["ProfileSeries"];
        };
        /**
         * ProfileSeries
         * @description An hourly ``EnergyProfile`` as parallel arrays, ready to chart.
         */
        ProfileSeries: {
            /** Source */
            source: string;
            /** Timestamps */
            timestamps: string[];
            /** Power Mw */
            power_mw: number[];
            /** Total Energy Mwh */
            total_energy_mwh: number;
        };
        /**
         * ScreeningSummary
         * @description Everything a client needs after creating or looking up a screening.
         *
         *     Area/warning/finding fields are ``None`` until the run has a result
         *     (e.g. while ``status`` is ``pending``/``running``, or if it ``failed``
         *     before producing one) — mirrors the CLI's own summary, just as JSON.
         */
        ScreeningSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Technology */
            technology: string;
            /** Country */
            country: string;
            /** Status */
            status: string;
            /** Created At */
            created_at?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Initial Area Square Meters */
            initial_area_square_meters?: number | null;
            /** Excluded Area Square Meters */
            excluded_area_square_meters?: number | null;
            /** Available Area Square Meters */
            available_area_square_meters?: number | null;
            /** Warnings */
            warnings?: number | null;
            /** Findings */
            findings?: components["schemas"]["FindingSummary"][];
        };
        /**
         * SolarResult
         * @description Outcome of ``POST /v1/screenings/{id}/solar-array``.
         */
        SolarResult: {
            /** Module Manufacturer */
            module_manufacturer: string;
            /** Module Model */
            module_model: string;
            /** Ground Coverage Ratio */
            ground_coverage_ratio: number;
            /** Module Count */
            module_count: number;
            /** Installed Capacity Kwp */
            installed_capacity_kwp: number;
            /** Used Area M2 */
            used_area_m2: number;
            simulation?: components["schemas"]["SolarSimulationSummary"] | null;
        };
        /** SolarSimulationSummary */
        SolarSimulationSummary: {
            /** Simulator */
            simulator: string;
            /** Dc Energy Mwh */
            dc_energy_mwh: number;
            /** Ac Energy Mwh */
            ac_energy_mwh: number;
            /** Inverter Loss Mwh */
            inverter_loss_mwh: number;
            /** Inverter Loss Fraction */
            inverter_loss_fraction: number;
            ac_profile: components["schemas"]["ProfileSeries"];
        };
        /**
         * TechnologyResults
         * @description Every technology result stored for one screening so far.
         *
         *     Each field is ``None`` until its ``POST`` endpoint has run for this
         *     screening. Re-running wind or solar clears ``hybrid`` and ``battery``,
         *     and re-running hybrid clears ``battery``, so stored results never mix
         *     inputs from different runs.
         */
        TechnologyResults: {
            /**
             * Screening Id
             * Format: uuid
             */
            screening_id: string;
            wind?: components["schemas"]["WindResult"] | null;
            solar?: components["schemas"]["SolarResult"] | null;
            hybrid?: components["schemas"]["HybridResult"] | null;
            battery?: components["schemas"]["BatteryResult"] | null;
        };
        /**
         * TurbinePositionSummary
         * @description One turbine candidate, in the screening's metric analysis CRS.
         */
        TurbinePositionSummary: {
            /** X M */
            x_m: number;
            /** Y M */
            y_m: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WindResult
         * @description Outcome of ``POST /v1/screenings/{id}/turbine-layout``.
         *
         *     ``simulation`` is ``None`` when no wind resource was uploaded, or when
         *     no turbine fitted the available area (nothing to simulate).
         */
        WindResult: {
            /** Turbine Manufacturer */
            turbine_manufacturer: string;
            /** Turbine Model */
            turbine_model: string;
            /** Rated Power Kw */
            rated_power_kw: number;
            /** Rotor Diameter M */
            rotor_diameter_m: number;
            /** Spacing Rotor Diameters */
            spacing_rotor_diameters: number;
            /** Grid Spacing M */
            grid_spacing_m: number | null;
            /** Crs */
            crs: string;
            /** Turbine Count */
            turbine_count: number;
            /** Positions */
            positions: components["schemas"]["TurbinePositionSummary"][];
            simulation?: components["schemas"]["WindSimulationSummary"] | null;
        };
        /** WindSimulationSummary */
        WindSimulationSummary: {
            /** Simulator */
            simulator: string;
            /** No Wake Energy Mwh */
            no_wake_energy_mwh: number;
            /** Wake Energy Mwh */
            wake_energy_mwh: number;
            /** Wake Loss Mwh */
            wake_loss_mwh: number;
            /** Wake Loss Fraction */
            wake_loss_fraction: number;
            wake_profile: components["schemas"]["ProfileSeries"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_screenings_v1_screenings_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_screening_v1_screenings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_screening_v1_screenings_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_screening_v1_screenings__screening_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screening_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_screening_report_v1_screenings__screening_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screening_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_screening_layer_v1_screenings__screening_id__layers__layer__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screening_id: string;
                layer: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_technology_results_v1_screenings__screening_id__technologies_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screening_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnologyResults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_turbine_layout_v1_screenings__screening_id__turbine_layout_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screening_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_turbine_layout_v1_screenings__screening_id__turbine_layout_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WindResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_solar_array_v1_screenings__screening_id__solar_array_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screening_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_solar_array_v1_screenings__screening_id__solar_array_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolarResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_hybrid_v1_screenings__screening_id__hybrid_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screening_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_create_hybrid_v1_screenings__screening_id__hybrid_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HybridResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_battery_dispatch_v1_screenings__screening_id__battery_dispatch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screening_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_battery_dispatch_v1_screenings__screening_id__battery_dispatch_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatteryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
