/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Trivial liveness check.
         */
        get: operations["health__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/screenings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Screening
         * @description Create a screening.
         *
         *     Without ``DATABASE_URL`` (Step 1): runs synchronously, like the CLI, and
         *     returns ``201`` with the completed result. With ``DATABASE_URL`` (Step
         *     3): only validates the input, enqueues a job and returns ``202`` with a
         *     ``pending`` summary — a worker process picks it up and ``GET`` polls for
         *     the outcome.
         */
        post: operations["create_screening_v1_screenings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/screenings/{screening_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Screening
         * @description Look up a previously created screening by id.
         *
         *     ``screening_id`` is either an ``AnalysisRun`` id (sync mode, or async
         *     mode once resolved) or — only when the job queue is enabled — a job id
         *     that has not resolved to a run yet (``pending``/``running``).
         */
        get: operations["get_screening_v1_screenings__screening_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/screenings/{screening_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Screening Report
         * @description Render the plain-text report for a completed screening.
         */
        get: operations["get_screening_report_v1_screenings__screening_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/screenings/{screening_id}/layers/{layer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Screening Layer
         * @description Return one result layer as GeoJSON, for map display.
         */
        get: operations["get_screening_layer_v1_screenings__screening_id__layers__layer__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_screening_v1_screenings_post */
        Body_create_screening_v1_screenings_post: {
            /**
             * Site
             * @description Granica terenu (GeoJSON)
             */
            site: string;
            /**
             * Constraints
             * @description Warstwy ograniczeń (GeoJSON)
             */
            constraints: string;
            /**
             * Rules
             * @description Konfiguracja reguł (YAML)
             */
            rules: string;
            /** Technology */
            technology: string;
            /**
             * Country
             * @default PL
             */
            country: string;
            /** Analysis Date */
            analysis_date?: string | null;
        };
        /**
         * FindingSummary
         * @description One constraint finding, shaped for JSON responses.
         */
        FindingSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Constraint Id
             * Format: uuid
             */
            constraint_id: string;
            /** Level */
            level: string;
            /** Status */
            status: string;
            /** Data Source */
            data_source: string;
            /** Data Version */
            data_version: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ScreeningSummary
         * @description Everything a client needs after creating or looking up a screening.
         *
         *     Area/warning/finding fields are ``None`` until the run has a result
         *     (e.g. while ``status`` is ``pending``/``running``, or if it ``failed``
         *     before producing one) — mirrors the CLI's own summary, just as JSON.
         */
        ScreeningSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Site Id
             * Format: uuid
             */
            site_id: string;
            /** Technology */
            technology: string;
            /** Country */
            country: string;
            /** Status */
            status: string;
            /** Error Message */
            error_message?: string | null;
            /** Initial Area Square Meters */
            initial_area_square_meters?: number | null;
            /** Excluded Area Square Meters */
            excluded_area_square_meters?: number | null;
            /** Available Area Square Meters */
            available_area_square_meters?: number | null;
            /** Warnings */
            warnings?: number | null;
            /** Findings */
            findings?: components["schemas"]["FindingSummary"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_screening_v1_screenings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_screening_v1_screenings_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_screening_v1_screenings__screening_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screening_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_screening_report_v1_screenings__screening_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screening_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_screening_layer_v1_screenings__screening_id__layers__layer__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screening_id: string;
                layer: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
